-
  uriPattern: 'stripe/payment/{orderNumber}'
  defaults:
    '@package': 'NeosRulez.Shop.Payment.Stripe'
    '@controller': 'Stripe'
    '@action': 'payment'
  appendExceedingArguments: true

-
  uriPattern: 'stripe/webhook'
  defaults:
    '@package': 'NeosRulez.Shop.Payment.Stripe'
    '@controller': 'Stripe'
    '@action': 'webhook'
  appendExceedingArguments: true

-
  uriPattern: 'stripe/test/webhook/{orderNumber}'
  defaults:
    '@package': 'NeosRulez.Shop.Payment.Stripe'
    '@controller': 'Stripe'
    '@action': 'webhookTest'
  appendExceedingArguments: true
